extends "res://tests/regular_play_test.gd"

func run():
	var scene=load("res://assets/scenes/game_scene/tactical_board_ui.tscn").instantiate()
	get_tree().root.add_child(scene)
	scene.set_process(false)
	scene._local_player_id=0
	var d=setup(6,12)
	var c=d.hand_cards.duplicate()
	check(RegularPlay.submit_group(0,[c[0],c[1]],[false,false]),"ordinary pair committed")
	var adapter:=DebugCardAdapter.new()
	check(adapter.move_card(c[2].get_instance_id(),"played_cards",0).ok,"console moves third card")
	check(RegularPlay.completed(0) and RegularPlay.played_count(0)==2,"move preserves ordinary completion and count")
	check(RegularPlay.pending_modes(0,[],[],c[3]).is_empty(),"no ordinary selection after pair and moved extra")
	check(not RegularPlay.submit_group(0,[c[3],c[4]],[false,false]),"no second ordinary group after moved extra")
	d=setup(6,12); c=d.hand_cards.duplicate()
	check(adapter.move_card(c[2].get_instance_id(),"played_cards",0).ok,"extra moved before ordinary selection")
	scene._choose_regular_play_mode(c[0],false)
	scene._choose_regular_play_mode(c[1],false)
	scene._choose_regular_play_mode(c[3],false)
	check(scene._regular_play_pending_cards.size()==2,"UI still limits pending ordinary pair alongside extra")
	scene._on_tactical_confirm_execute()
	check(RegularPlay.completed(0) and d.played_cards.size()==3,"pair plus moved extra stays three")
	d=setup(6,12); c=d.hand_cards.duplicate()
	check(RegularPlay.add(0,c[0],false),"incremental first ordinary card")
	check(adapter.move_card(c[2].get_instance_id(),"played_cards",0).ok,"move extra during incomplete ordinary flow")
	check(RegularPlay.pending_modes(0,[c[1]],[false],c[3]).is_empty(),"pending group counts previously committed ordinary card")
	check(not RegularPlay.can_submit_group(0,[c[1],c[3]],[false,false]),"mixed entrances cannot exceed ordinary limit")
	check(RegularPlay.can_submit_group(0,[c[1]],[false]),"remaining single ordinary card can complete flow")
	check(RegularPlay.submit_group(0,[c[1]],[false]),"remaining ordinary card submitted")
	check(d.played_cards.size()==3 and RegularPlay.played_count(0)==2,"mixed entrances preserve pair plus extra")
	check(GameLog.query({"type":"regular_play","actor":0},0)[0].data.count==2,"completion records total ordinary count")
	d=setup(6,12); c=d.hand_cards.duplicate(); d.play_limit.number=4
	check(RegularPlay.add(0,c[0],false),"declared higher limit accepts first card")
	check(PlayAttack.new().exec(c[4],0,null,null,true),"effect extra accepted during ordinary flow")
	check(RegularPlay.can_submit_group(0,[c[1],c[2],c[3]],[false,false,false]),"declared higher limit still permits remaining three")
	check(RegularPlay.submit_group(0,[c[1],c[2],c[3]],[false,false,false]),"higher limit group completes")
	check(RegularPlay.played_count(0)==4 and d.played_cards.size()==5,"effect extra does not spend ordinary allowance")
	check(RegularPlay.pending_modes(0,[],[],c[5]).is_empty(),"higher limit remains enforced after extra")
	print("RESULT checks=",checks," failures=",failures)
	get_tree().quit(0 if failures.is_empty() else 1)
